version: '3'

networks:
  notifymicroservice:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: notifymicroservice-nginx
    ports:
      - "8083:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - notifymicroservice


  mysql:
    image: mysql:5.7.22
    container_name: notifymicroservice-mysql
    restart: always
    tty: true
    ports:
      - "4303:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_USER: kwafodev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - notifymicroservice
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifymicroservice-php
    volumes:
      - ../src:/var/www/html
    ports:
      - "9004:9000"
    networks:
      - notifymicroservice